// data generated by gpt...not that sad lol
let keywords = [
    "How to lose weight",
    "How to make money",
    "What is love",
    "How to tie a tie",
    "What is my IP address",
    "What is my location",
    "What time is it",
    "What is the weather today",
    "How to cook rice",
    "How to boil an egg",
    "What is the meaning of life",
    "How to kiss",
    "How to write a resume",
    "How to invest in stocks",
    "How to play chess",
    "What is Bitcoin",
    "How to meditate",
    "How to draw",
    "What is the capital of the United States",
    "What is the meaning of my name",
    "How to make pancakes",
    "How to make pizza",
    "What is the meaning of Christmas",
    "What is the meaning of Easter",
    "How to code",
    "How to start a business",
    "What is the stock market",
    "How to clean a laptop screen",
    "How to clean a washing machine",
    "How to clean a carpet",
    "What is the best smartphone",
    "How to use Excel",
    "How to use Photoshop",
    "How to use TikTok",
    "What is the meaning of art",
    "How to do a handstand",
    "How to do a split",
    "How to do yoga",
    "What is the meaning of success",
    "How to be happy",
    "How to learn a new language",
    "What is the meaning of friendship",
    "What is the meaning of family",
    "What is the meaning of education",
    "How to find a job",
    "How to make friends",
    "How to stop procrastinating",
    "How to overcome anxiety",
    "How to overcome depression",
    "How to stop snoring",
    "How to stop a headache",
    "What is the meaning of happiness",
    "What is the meaning of peace",
    "What is the meaning of freedom",
    "What is the meaning of democracy",
    "What is the meaning of justice",
    "What is the meaning of equality",
    "What is the meaning of human rights",
    "What is the meaning of sustainability",
    "What is the meaning of climate change",
    "What is the meaning of biodiversity"
  ];
let input = document.getElementById("search-input");
let result_box = document.querySelector(".result-box");

input.addEventListener("keyup", ()=>{
    let searchValue = input.value
    let results = []
    if(searchValue.length){
    results = keywords.filter((item)=>{
        return item.toLocaleLowerCase().includes(searchValue.toLocaleLowerCase())
    })
    displayResults(results)
}
    if(!searchValue.length){
     result_box.innerHTML = ""
    }
})

function displayResults(list){
let resultList = list.map((item)=>{
     return `<li onclick = "updateResult(this)">${item}</li>`;
})
result_box.innerHTML = "<ul>" + resultList.join("") + "</ul>";
}


function updateResult(value){
input.value = value.innerHTML
result_box.innerHTML = ''
}


